config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'google_books#index'

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end

  devise_for :users
  resources :reviews
  resources :google_books do
    collection do
      get :search
    end
  end
  resources :books do
    member do
      patch :move
      patch :select
    end
    collection do
      get :search
    end
    resources :reviews, only: %i[index]
  end
  get ':username', to: 'users#show', as: 'user'
  get ':username/books', to: 'books#index', as: 'user_books'
  get ':username/reviews', to: 'reviews#index', as: 'user_reviews'
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <%= link_to root_path do %>
    <%= image_tag('logo.svg', size: '130x50') %>
  <% end %>
  <%= render "layouts/navbar_dropdown" %>
</header>

app/views/layouts/_navbar_dropdown.html.erb
<div class="dropdown navbar_dropdown"
     data-controller="dropdown"
     data-dropdown-active-target="#navbar_menu">
  <div role="button" tabindex="0">
    <input data-action="click->dropdown#toggle click@window->dropdown#hide" data-dropdown-target="checkbox" class="menu-trigger hidden" id="togglenav" type="checkbox"/>
    <label class="burger-wrapper" for="togglenav">
      <div class="hamburger"></div>
    </label>
  </div>
  <div id="dropdown_menu" data-dropdown-target="menu" class="dropdown__menu dropdown__menu--right" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
    <div>
      <a data-action="click->dropdown#toggle" class="dropdown__menu_item" href="/">Home</a>
      <%= link_to "All books", books_path, data: {action: "click->dropdown#toggle"},
          class: "dropdown__menu_item" %>
      <%= link_to "All reviews", reviews_path, data: {action: "click->dropdown#toggle"},
          class: "dropdown__menu_item" %>
    </div>
    <% if user_signed_in? %>
      <div class="dropdown__menu_section">
        <a data-action="click->dropdown#toggle" class="dropdown__menu_item"
          href="<%= url_for(controller: '/books', action: 'index', username: current_user.username)%>">Your Books</a>
        <a data-action="click->dropdown#toggle" class="dropdown__menu_item"
          href="<%= url_for(controller: '/reviews', action: 'index', username: current_user.username)%>">Your Reviews</a>
      </div>
    <% else %>
      <div class="dropdown__menu_section">
        <%= link_to "Log In",
          new_user_session_path,
          class:"dropdown__menu_item" %>
        <%= link_to "Sign Up",
          new_user_registration_path,
          class:"dropdown__menu_item" %>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <div class="dropdown__menu_section">
        <a data-action="click->dropdown#toggle" class="dropdown__menu_item"
          href="<%= url_for(controller: '/users', action: 'show', username: current_user.username)%>">Profile</a>
        <a data-action="click->dropdown#toggle" class="dropdown__menu_item" href="/users/edit">Settings</a>
        <a data-action="click->dropdown#toggle" data-turbo-method="delete" class="dropdown__menu_item" href="/users/sign_out">Sign Out</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_profile_section.html.erb
<div class="container">
  <header class="profile_section">
    <section>
      <a href="/<%= @user.username %>"></a>
    </section>
    <section>
      <%= link_to @user.username, user_url(username: @user.username), class:"profile_section__username" %>
    </section>

    <div class="profile_section__summary">
      <a href="/<%= @user.username %>/books">
        <span class="summary__count"><%= @user.books.count %></span>
        <span class="block text-sm mt-1">Books</span>
      </a>
      <a href="/<%= @user.username %>/reviews">
        <span class="summary__count"><%= @user.reviews.count %></span>
        <span class="block text-sm mt-1">Reviews</span>
      </a>
    </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Bookshelf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body class="application">
    <%= render "layouts/navbar" %>

    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>
    <%= yield %>
  </body>
</html>